spring.application.name=tecnologia_tienda_productos

### Configuración BD Oracle XE 21c
# Conexión Oracle XE 21c PDB XEPDB1
#spring.datasource.url=jdbc:oracle:thin:@//192.168.1.35:1521/XEPDB1
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1 
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
